name: Generate Code Graph

on:
  push:
    branches:
      - main

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Generate Graph
        run: |
          dot -Tpng project_structure.dot -o output.png
